// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Palette, VerticalBox } from "std-widgets.slint";

component SideBarItem inherits Rectangle {
    in property <bool> selected;
    in property <bool> has-focus;
    in-out property <string> text <=> label.text;
    callback clicked <=> touch.clicked;
    min-height: self.visible ? l.preferred-height : 0px;
    // min-width: self.visible ? l.preferred-width + 10px : 0px;
    states [
        pressed when touch.pressed: {
            state.opacity: 0.8;
        }
        hover when touch.has-hover: {
            state.opacity: 0.6;
        }
        selected when root.selected: {
            state.opacity: 1;
        }
        focused when root.has-focus: {
            state.opacity: 0.8;
        }
    ]

    state := Rectangle {
        opacity: 0;
        background: Palette.selection-background;
        animate opacity { duration: 150ms; }
        height: 100%;
    }

    l := HorizontalLayout {
        x: 4px;
        y: (parent.height - self.height) / 2;
        padding-left: 8px;
        padding-right: 8px;
        padding-top: 6px;
        padding-bottom: 6px;
        spacing: 0px;
        label := Text {
            color: Palette.foreground;
            vertical-alignment: center;
            font-size: 14px;
        }
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}

export component SideBar inherits Rectangle {
    in property <[string]> model: [];
    in property <[bool]> available: [];
    in property <bool> is_tuf: false;
    out property <int> current-item: 0;
    out property <int> current-focused: fs.has-focus ? fs.focused-tab : -1;

    // The currently focused tab
    width: 180px;
    forward-focus: fs;
    accessible-role: tab;
    accessible-delegate-focus: root.current-focused >= 0 ? root.current-focused : root.current-item;
    Rectangle {
        background: Palette.alternate-background;
        fs := FocusScope {
            key-pressed(event) => {
                if (event.text == "\n") {
                    root.current-item = root.current-focused;
                    return accept;
                }
                if (event.text == Key.UpArrow) {
                    self.focused-tab = Math.max(self.focused-tab - 1,  0);
                    return accept;
                }
                if (event.text == Key.DownArrow) {
                    self.focused-tab = Math.min(self.focused-tab + 1, root.model.length - 1);
                    return accept;
                }
                return reject;
            }
            key-released(event) => {
                if (event.text == " ") {
                    root.current-item = root.current-focused;
                    return accept;
                }
                return reject;
            }
            property <int> focused-tab: 0;
            x: 0;
            width: 0;
            // Do not react on clicks
        }
    }

    VerticalBox {
        spacing: 4px;
        padding: 0px;
        alignment: start;

        Image {
            height: 100px;
            // TODO: change if TUF on the logo in the menu on the main page
            // If running on a TUF model, replace the ROG red with TUF orange
            // (add data/tuf-control-center.png and switch here when available)
            source: @image-url("../../data/rog-control-center.png");
            horizontal-alignment: center;
            image-fit: contain;
        }

        Rectangle {
            height: 1px;
            background: Palette.border;
        }

        navigation := VerticalLayout {
            spacing: 2px;
            alignment: start;
            vertical-stretch: 0;
            for item[index] in root.model: SideBarItem {
                visible: root.available[index];
                clicked => {
                    root.current-item = index;
                }
                has-focus: index == root.current-focused;
                text: item;
                selected: index == root.current-item;
            }
        }

        VerticalLayout {
            bottom := VerticalBox {
                padding-left: 0px;
                padding-top: 0px;
                padding-bottom: 0px;
                @children
            }
        }
    }
}
