[workspace.package]
version = "6.3.9"
rust-version = "1.82"
license = "MPL-2.0"
readme = "README.md"
authors = [
  "Luke <luke@ljones.dev>",
  "Denis Benato <benato.denis96@gmail.com>"
]
repository = "https://github.com/OpenGamingCollective/asusctl"
homepage = "https://github.com/OpenGamingCollective/asusctl"
description = "Laptop feature control for ASUS ROG laptops and others"
edition = "2021"

[workspace]
resolver = "2"
members = [
  "asusctl",
  "asusd",
  "asus-shutdown",
  "asusd-user",
  "config-traits",
  "dmi-id",
  "rog-platform",
  "rog-dbus",
  "rog-anime",
  "rog-aura",
  "rog-profiles",
  "rog-control-center",
  "rog-slash",
  "simulators",
  "rog-scsi",
]

default-members = ["asusctl", "asusd", "asus-shutdown", "asusd-user", "rog-control-center"]

[workspace.dependencies]
argh = "^0.1"
ashpd = { version = "^0.13", default-features = false, features = ["async-io", "global_shortcuts"] }
concat-idents = "^1.1"
console-subscriber = "^0.4"
dirs = "^4.0"
env_logger = "^0.10.0"
futures-util = "^0.3.31"
gif = "^0.12"
glam = { version = "^0.22", features = ["serde"] }
gumdrop = "^0.8"
image = "^0.25.5"
inotify = "^0.10"
ksni = { version = "^0.3", default-features = false, features = ["async-io"] }
libc = "^0.2"
log = "^0.4"
logind-zbus = { version = "^5.2.0" }
mio = "^0.8.11"
nix = { version = "^0.29", features = ["uio"] }
notify-rust = { version = "^4.11.5", features = ["z", "async"] }
nvml-wrapper = "^0.12.0"
pix = "^0.13"
png = "^0.17"
png_pong = "^0.8"
ron = "*"
rusb = "^0.9"
sdl2 = { version = "^0.37", default-features = false }
serde = { version = "^1.0", features = ["serde_derive"] }
serde_json = "^1.0"
slint = { version = "^1.17.1", features = ["gettext"] }
slint-build = "^1.17.1"
thiserror = "^2"
tokio = { version = "^1.39.0", default-features = false, features = [
  "macros",
  "sync",
  "time",
  "rt",
  "rt-multi-thread",
] }
udev = { version = "^0.8", features = ["mio"] }
uhid-virt = "^0.0.8"
zbus = "^5.13.1"

[profile.release]
lto = "thin"
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
opt-level = 1

[workspace.dependencies.cargo-husky]
version = "^1"
default-features = false
features = ["user-hooks"]
